spring:
  security:
    oauth2:
      client:
        registration:
          client-server-oidc:
            provider: spring
            client-id: client-server
            client-secret: secret
            authorization-grant-type: authorization-code
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            scope: openid, profile
            client-name: client-server-oidc
        provider:
          spring:
            issuer-uri: http://localhost:9000
